### ISSUE TITLE
Wrong heading levels in the data model documentation

### ISSUE THREAD

**Issue by vkucera** [AliceO2Group/O2Physics#2056]
Hi @pbuehler , could you please fix the wrong heading levels in the generated data model documentation?
See the error details in the MegaLinter log: https://github.com/AliceO2Group/analysis-framework/actions/runs/4248893181/jobs/7388526270

**Comment by pbuehler** [comment]
@vkucera I guess this is obsolete?

**Comment by vkucera** [comment]
> @vkucera I guess this is obsolete?

I realised this is not the right repository, so I closed this one and created another one in O2: https://github.com/AliceO2Group/AliceO2/issues/10823
