### ISSUE TITLE
PWGHF: Add particle origin in the tree creator tables

### ISSUE THREAD

**Issue by vkucera** [AliceO2Group/O2Physics#2392]
- [x] `treeCreatorChicToJpsiGamma` Fixed in 2391
- [x] `treeCreatorD0ToKPi` @atavirag Fixed in 2229
- [x] `treeCreatorLbToLcPi` Fixed in 2391
- [x] `treeCreatorLcToK0sP` @DanielSamitz Fixed in 2657
- [x] `treeCreatorLcToPKPi` Fixed in 2391
- [x] `treeCreatorXToJpsiPiPi` Fixed in 2391
- [x] `treeCreatorXiccToPKPiPi` Fixed in 2391

PRs:
- @DelloStritto https://github.com/AliceO2Group/O2Physics/pull/2391
- @DanielSamitz https://github.com/AliceO2Group/O2Physics/pull/2657
- @atavirag https://github.com/AliceO2Group/O2Physics/pull/2229

**Comment by apalasciano** [comment]
Dear Vit,
I have just a side question related to this PR.
I was wondering if it was really useful to have a origin column for B/Lb
mesons.
As far as I understood, it should be used to track prompt and feed-down
components of  charmed baryons.
Unless we want to track decays of possible heavier beauty states, I don't
think it's really necessary for B or Lb. Also I see that for the Lb it's
always set to zero.
In case it's needed to have a uniform style of the tree, I'll propagate the
modifications also to the B creator.
Let me know what you think

Cheers,
Antonio

Il giorno ven 14 apr 2023 alle ore 20:59 Vít Kučera <
***@***.***> ha scritto:
