### ISSUE TITLE
Move OTF software to dedicated directory

### ISSUE THREAD

**Issue by njacazio** [AliceO2Group/O2Physics#3383]
@ddobrigk @hscheid in order to make some order into the ALICE3 and since activities are quickly ramping up we should separate the OTF software now. It's a dedicated topic and we should treat it as such.
What do you think to move it under e.g. `ALICE3/TableProducer/OTF`?

**Comment by njacazio** [comment]
e.g. something like https://github.com/AliceO2Group/O2Physics/pull/3384

**Comment by hscheid** [comment]
Hi @njacazio I think this is an excellent idea. At least for now.

**Comment by njacazio** [comment]
indeed we could think about moving it out of the A3 scope once it is ripe

**Comment by njacazio** [comment]
Done!
