### ISSUE TITLE
PWGHF: extend RecoDecay::getCharmHadronOrigin functionality

### ISSUE THREAD

**Issue by fcatalan92** [AliceO2Group/O2Physics#6051]
Extend the functionality of `RecoDecay::getCharmHadronOrigin` to return the index of the found mother, which is useful to retrieve, e.g., the pT of the mother B hadron, and remove the code duplication introduced in https://github.com/AliceO2Group/O2Physics/pull/6017.
@Mingyu3360715 @atavirag

**Comment by fgrosa** [comment]
`RecoDecay::getCharmHadronOrigin` was modified in this https://github.com/AliceO2Group/O2Physics/pull/6162, adding the functionality to retrieve the B-mother pT for the D*. It can be used as an example also for the D0 code @Mingyu3360715 @atavirag
